config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :phrases
  root 'application#index'
  namespace 'api' do
    namespace 'v1' do
      resources :phrases
      get 'setup', to: 'phrases#setup'
      get 'categories', to: 'phrases#categories'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :phrases, dependent: :delete_all
  has_many :translations, through: :phrases
  validates :name, uniqueness: true
end

app/models/phrase.rb
class Phrase < ApplicationRecord
  has_one_attached :demonstration
  belongs_to :category
  has_many :translations, dependent: :destroy
  accepts_nested_attributes_for :translations, allow_destroy: true

  def word
    if translations.where(language: 'es').first.nil?
      if translations.where(language: 'en').first.nil?
        translations.first
      else
        translations.where(language: 'en').first
      end
    else
      translations.where(language: 'es').first
    end
  end
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :phrase
end

app/controllers/api/v1/phrases_controller.rb
module Api
  module V1
    class PhrasesController < ApplicationController
      def setup
        phrase = Phrase.all.order(:day)
        start_date = phrase.first.day
        end_date = phrase.last.day
        render json: {start_date: start_date, end_date: end_date}, status: :ok
      end
      def show
        phrase = Phrase.find_by_day(params[:id])

        if phrase.nil?
          render json: { error: 'No phrase for that day.' }, status: 404
        else
          response = {
              id: phrase.id,
              category: phrase.category.name,
              demonstration: url_for(phrase.demonstration),
              translations: []
          }
          phrase.translations.each do |translation|
            response[:translations].push(id: translation.id, translation: translation.content, definition: translation.definition, language: translation.language)
          end
          render json: response, status: :ok
        end
      end
      def categories
        data = []
        categories = Category.all
        categories.each do |category|
          info = { title: category.name, content: [] }
          category.phrases.where('day <= ?', Date.today).each do |phrase|
            info[:content].push({ title: phrase.word.content, date: phrase.day, demonstration: url_for(phrase.demonstration) })
          end
          data.push(info)
        end
        render json: data, status: :ok
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @categories = Category.all
    @phrases = Phrase.all
    @category = params[:category]
    @phrase = params[:phrase]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:destroy]
  def new
    @category = Category.new
  end

  def show
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.js
        format.html { redirect_to root_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to root_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  before_action :set_phrase, only: [:show, :edit, :update, :destroy]
  before_action :get_languages, only: [:show, :create, :new, :edit, :update]

  # GET /phrases
  # GET /phrases.json
  def index
    @phrases = Phrase.all
  end

  # GET /phrases/1
  # GET /phrases/1.json
  def show
  end

  # GET /phrases/new
  def new
    @phrase = Phrase.new
    @categories = Category.all.order(:name)
  end

  # GET /phrases/1/edit
  def edit
    @categories = Category.all.order(:name)
  end

  # POST /phrases
  # POST /phrases.json
  def create
    @phrase = Phrase.new(phrase_params)

    respond_to do |format|
      if @phrase.save
        format.html { redirect_to root_path(category: @phrase.category, phrase: @phrase), notice: 'Phrase was successfully created.' }
        format.json { render :show, status: :created, location: @phrase }
      else
        format.html { render :new }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phrases/1
  # PATCH/PUT /phrases/1.json
  def update
    respond_to do |format|
      if @phrase.update(phrase_params)
        format.html { redirect_to root_path(category: @phrase.category, phrase: @phrase), notice: 'Phrase was successfully updated.' }
        format.json { render :show, status: :ok, location: @phrase }
      else
        format.html { render :edit }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phrases/1
  # DELETE /phrases/1.json
  def destroy
    @phrase.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to root_path, notice: 'Phrase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phrase
      @phrase = Phrase.find(params[:id])
      @categories = Category.all.order(:name)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phrase_params
      params.require(:phrase).permit(:day, :category_id, :demonstration, :translations_attributes => [:id, :language, :content, :definition, :_destroy])
    end

  def get_languages
    @data = JSON.parse(File.read('public/languages.json'))
    @categories = Category.all.order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: 'add_fields btn btn-outline-secondary btn-sm', data: { id: id, fields: fields.gsub('\n', '') })
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/views/application/_categoryPhrases.html.erb
<div class="tab-pane fade <%= @category == categoryPhrases.id.to_s ? "active show" : "" %>" id="v-pills-c<%= categoryPhrases.id %>" role="tabpanel" aria-labelledby="v-pills-c<%= categoryPhrases.id %>-tab">
  <div class="row">
    <div class="col-4">
      <div class="nav flex-column nav-pills phrases" id="v-pills-tab-c<%= categoryPhrases.id %>" role="tablist" aria-orientation="vertical">
        <% if categoryPhrases.phrases.count != 0 %>
          <%= render partial: 'phrases/phrase', collection: categoryPhrases.phrases %>
        <% else %>
          No phrases available
        <% end %>
      </div>
      <br/>
      <%= link_to 'New Phrase', new_phrase_path(category_id: categoryPhrases.id), class: 'btn btn-outline-link' %>
    </div>
    <div class="col-8">
      <div class="tab-content" id="v-pills-tabContent-c<%= categoryPhrases.id %>">
        <%= render partial: 'phrases/show', collection: categoryPhrases.phrases %>
      </div>
    </div>
  </div>
</div>

app/views/application/index.html.erb
<h1 align="center"><b>Daily Sign</b></h1>

<hr/>

<div class="row">
  <div class="col-3">
    <h3>Categories</h3>
    <div class="nav flex-column nav-pills categories" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <%= render partial: 'categories/category', collection: @categories %>
    </div>
    <br/>
    <div id="new-category">
      <%= link_to 'New Category', new_category_path, class: 'btn btn-outline-link', remote: true %>
    </div>
  </div>
  <div class="col-9">
    <h3>Phrases</h3>
    <div class="tab-content" id="v-pills-tabContent">
      <%= render partial: 'categoryPhrases', collection: @categories %>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<a class="nav-link <%= @category == category.id.to_s ? "active" : "" %>" id="v-pills-c<%= category.id %>-tab" data-toggle="pill" href="#v-pills-c<%= category.id %>" role="tab" aria-controls="v-pills-c<%= category.id %>" aria-selected="false">
  <%= category.name %>
</a>
<%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?', remote: true, target: 'v-pills-c' + category.id.to_s + '-tab', children: 'v-pills-c' + category.id.to_s }, class: 'categoryDelete', hidden: true %>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, class: 'form-control', placeholder: 'New Category', autocomplete: :off %>
  </div>

  <div class="actions">
    <%= form.submit hidden: true %>
  </div>
<% end %>

app/views/categories/create.js.erb
$('#new-category form').remove();
$('#new-category a').show();
$('div#v-pills-tab').append('<%= j render @category %>')
$('div#v-pills-tabContent').append('<%= j render partial:'application/categoryPhrases', object: @category %>')

app/views/categories/destroy.js.erb
$('.categoryDelete').bind('ajax:success', function () {
    let target = $(this).data('target');
    $('#' + target)[0].remove();
    let children = $(this).data('children');
    $('#' + children)[0].remove();
    $(this).remove();
});

app/views/categories/new.js.erb
$('#new-category a').hide().parent().append('<%= j render 'form', category: @category %>')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailySign</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/gijgo@1.9.11/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.11/css/gijgo.min.css" rel="stylesheet" type="text/css" />
  </head>

  <body>
  <div class="col-sm-12 col-xl-10 offset-xl-1 main">
    <%= yield %>
  </div>
  </body>
</html>

app/views/phrases/_form.html.erb
<%= form_with(model: phrase, local: true) do |form| %>
  <% if phrase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phrase.errors.count, "error") %> prohibited this phrase from being saved:</h2>

      <ul>
      <% phrase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="col">
      <div class="form-group">
        <%= form.label :day, 'Date' %>
        <%= form.text_field :day, id: 'datepicker', autocomplete: :off, required: true %>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <%= form.label :demonstration %>
        <div class="custom-file">
          <%= form.file_field :demonstration, class: 'custom-file-input', id: 'customFile' %>
          <label class="custom-file-label" for="customFile"></label>
        </div>
      </div>
    </div>
  </div>

  <%= form.text_field :category_id, value: params[:category_id], hidden: true %>

  <div class="form-group">
    <%= form.fields_for :translations do |builder| %>
      <%= render 'translation_fields', f: builder %>
    <% end %>
    <%= link_to_add_fields "Add Translation", form, :translations %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-outline-success' %>
  </div>
<% end %>

app/views/phrases/_phrase.html.erb
<a class="nav-link <%= @phrase == phrase.id.to_s ? "active" : "" %>" id="v-pills-<%= phrase.id %>-tab" data-toggle="pill" href="#v-pills-<%= phrase.id %>" role="tab" aria-controls="v-pills-<%= phrase.id %>" aria-selected="false">
  <%= phrase.word.content %>
</a>
<%= link_to 'Destroy', phrase, method: :delete, data: { remote: true, target: 'v-pills-' + phrase.id.to_s + '-tab' }, class: 'phraseDelete', hidden: true %>

app/views/phrases/_show.html.erb
<div class="tab-pane fade <%= @phrase == show.id.to_s ? "active show" : "" %>" id="v-pills-<%= show.id %>" role="tabpanel" aria-labelledby="v-pills-<%= show.id %>-tab">
  <div class="card" style="width: 80%; margin-left: 10%">
    <% if show.demonstration.attached? %>
      <%= image_tag(show.demonstration, class: 'card-img-top') %>
    <% end %>
    <div class="card-body">
      <h3 class="card-title"><%= show.word.content %></h3>
      <h6 class="card-subtitle mb-2 text-muted"><%= show.day %></h6>
      <p class="card-text"><%= show.word.definition %></p>
      <table class="table">
        <thead>
        <tr>
          <th></th>
          <th>Phrase</th>
          <th>Definition</th>
        </tr>
        </thead>
        <tbody>
        <% show.translations.each do |translation| %>
          <tr>
            <td><%= translation.language %></td>
            <td><%= translation.content %></td>
            <td><%= translation.definition %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to 'Edit', edit_phrase_path(show, category_id: show.category), class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/phrases/_translation_fields.html.erb
<div class="translation">
  <div class="form-row">
    <div class="col-sm-12 col-xl-2">
      <%= f.select :language, @data.map {|v| [ v['name'].split(';').first.split(',').first, v['code'] ] }, {}, { :class => 'form-control' } %>
    </div>
    <div class="col-sm-6 col-xl-3">
      <%= f.text_field :content, class: 'form-control', placeholder: 'Content', required: true %>
    </div>
    <div class="col-sm-6 col-xl-6">
      <%= f.text_field :definition, class: 'form-control', placeholder: 'Definition', required: true %>
    </div>
    <div class="col-sm-12 col-xl-1">
      <%= f.hidden_field :_destroy %>
      <%= link_to 'remove', '#', class: 'btn btn-outline-secondary btn-block remove_fields' %>
    </div>
  </div>
  <br/>
</div>

app/views/phrases/destroy.js.erb
$('.phraseDelete').bind('ajax:success', function () {
    let target = $(this).data('target');
    $('#' + target)[0].remove();
    $(this).remove();
});

app/views/phrases/edit.html.erb
<h1>Editing Phrase</h1>

<%= render 'form', phrase: @phrase %>

app/views/phrases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phrases</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phrases.each do |phrase| %>
      <tr>
        <td><%= phrase.day %></td>
        <td><%= phrase.category.name %></td>
        <td><%= link_to 'Show', phrase %></td>
        <td><%= link_to 'Edit', edit_phrase_path(phrase) %></td>
        <td><%= link_to 'Destroy', phrase, method: :delete, data: { remote: true }, class: 'phraseDelete' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phrase', new_phrase_path %>

app/views/phrases/new.html.erb
<h1>New Phrase</h1>

<%= render 'form', phrase: @phrase %>

app/views/phrases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @phrase.day %>
</p>

<p>
  <strong>Category:</strong>
  <%= @phrase.category.name %>
</p>

<%= link_to 'Edit', edit_phrase_path(@phrase) %> |
<%= link_to 'Back', phrases_path %>